### ISSUE TITLE
"Execute code when the document is ready" code block formatting

### ISSUE THREAD

**Issue by KrastanD** [phuocng/html-dom#284]
The code isn't in a code block. It looks like regular markdown \` ` instead of \``` ```

<img width="1059" alt="image" src="https://github.com/phuocng/html-dom/assets/32044675/ec5512bc-487f-4b46-bde6-b16191d712fd">
d

**Comment by phuocng** [comment]
@KrastanD Thank a lot for reporting the issue.
I have fixed it and included more contents for this post
https://phuoc.ng/collection/html-dom/execute-code-when-the-document-is-ready/
